#!/bin/bash

# (c) Yoan AGOSTINI <yoan {DOT IS HERE} agostini {AT IS HERE} gmail {DOT IS HERE} com>
# (c) Ronan LEBON
# (c) Ingesup

# MyWaf is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# MyWaf is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with MyWaf. If not, see http://www.gnu.org/licenses/.

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

ps `sudo cat /var/run/nginx-naxsi-ui_extract.pid` &> /dev/null

if [ $? -eq 0 ]; then
        echo -n "Naxsi UI Extract is OK ;"
        ps `sudo cat /var/run/nginx-naxsi-ui_intercept.pid` &> /dev/null
        if [ $? -ne 0 ]; then 
                echo -n "Naxsi UI Intercept is down ;"
                exit $STATE_CRITICAL
        fi      
        echo -n "Naxsi UI is fully running ;"
        exit $STATE_OK
else
        echo -n "Naxsi UI Extract is down ;"
        ps `sudo cat /var/run/nginx-naxsi-ui_intercept.pid` &> /dev/null
        if [ $? -ne 0 ]; then 
                echo -n "Naxsi UI Intercept is down ;"
        else
                echo -n "Naxsi UI Intercept is OK ;"
        fi      
        exit $STATE_CRITICAL
fi